---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: bar
  labels:
    app: nginx
spec:
  replicas: 1
  slector:
    matchLabels:
      app: nginx
  template:
    metdata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: arifh167/nginx:v0.1.0
          ports:
            - containerPort: 80